### ISSUE TITLE
Don't show Restart button on notifications for GNOME Shell crashes

### ISSUE THREAD

**Issue by mcatanzaro** [abrt/gnome-abrt#137] opened 2015-07-14 21:10 UTC
I have not yet dared to press the Restart button on the crash notifications that I see when GNOME Shell crashes. The fact that I can see the notification indicates that GNOME Shell has successfully recovered, so best not show the button in this case.

**Comment by xsuchy** [comment] 2017-05-11 12:33
Duplicate of https://github.com/abrt/gnome-abrt/issues/132

**Closed by xsuchy** 2017-05-11 12:33 UTC
